### ISSUE TITLE
#lang name

### ISSUE THREAD

**Issue by spdegabrielle** [Kalimehtar/russian-lang#3]
Hi, 
I was looking at the list of languages in the racket docs and I noticed this was listed as `#lang 1`
I'd like to suggest it is renamed `#lang Ади́на` ?

best regards
Stephen

**Comment by Kalimehtar** [comment]
I cannot. "The syntax of language is far more restricted than a module path, because only a-z, A-Z, 0-9, / (not at the start or end), _, -, and + are allowed in a language name." (https://docs.racket-lang.org/guide/hash-lang_syntax.html)

**Comment by Kalimehtar** [comment]
"1" in Russian is pronounced like "adin". So it is a wordplay.

**Comment by spdegabrielle** [comment]
Two very good reasons!
